---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale-system
spec:
  encryptedData:
    client_id: AgAHmO6ygq7Ul++xGHI+azRCHLackES5XhXm9+IPz4sbMOQ48/MXtKyVledLQlCEfvidt2SJUrGiRMhScf3Hv9I1dDz4hFn4evUJY++5zBeRLxpQqqFu9I2wrNMeRrvZ7ow5cwMprinDqK+pgFKJlTf6Gji0E/h/0d6b1BulLvrArNmCHUXV9SNkB8AnZ1wVqV+/9atupWI/9qxIgMdT2lsIurvBnIiAunBTFAOsTjLSwzFsLZCN6WfTyCTIcv3rBzvxB2yTleLMJQsIOxnDFDFCpLQKN3sjwF/BsziTWvPxfd7gKMAi4UVf2eo/B4GZ6jRW9qRdyyGPAqBa02vIg8SP+UMHexz/5XNx0gkfesg+7d8uEr6njZPzU8UyEeo8uBk9tp4fzTnmU6xHsbPGktHRQ0BLTov6pfIpWUnAlpTewef2pugqmbgSuBmtIA1sXtymm7U2ifr/EmjQvSAfkkD4ImXiY2L0iWBW/qzYktHl4RHkAcrjN8C+qUGHZvGTQ1DHNaiP4irl0Lm0h5VLqzzgMfFJys2M3Jy//5z+sdNTt9oSd/am3M9PF9XWojJo/Kr99gHqQmDg93qdEiFHPHhPsMeI6pldqmTzPjLBlsAh/tzGXjrw3cwMDT6wUf21mhBUlLkEp65A37r5dJXEsBDEz2E9nez6TNY+CnDsGeaG2e2TO25FqLfI6/dwiZTuBJB80K6ir+6P3AVJGICQNWLAsQ==
    client_secret: AgA9HzAO/T6mnOUYQlvzSxFJEUWAoDq17c4ZfhWnijR+SY+ShHpsom4nAb3NyLJxpbAmVINyuEs2aM9iYBot2wD0MvghevZDf1at/74BKAMQ0/wvBr6fAzkEIUnWKlIDn/AE3d+NoscdOGelN7tNboht1vJi5wcGgdYT/erIJB3Pq7VLdNNEodqAo+Hyu1Xi3hxgagF3+MhE8KNerM1lWU7t53BFbRhtolKyHAIROjqs41aBX/IbAMfqgjVJ1gncnt9kLA4cX4ZqskjDsLVPk7rAy/4nEITiyygSw/nA+ZAhoStRXVHvX/nZwRHWf1qViIJCAXMcrGcbBZW4VR/FhVFPTOUzP6z7b5JOksrgOQZUSEa1dJf73/W6kFJWCL2kHdeUq6XDAdY3PUTEuwPQyVEhbaEOBYd3p7Gr722zp05XCQpsAUHO3euEkzf2Cz0HJAxYB/jSPPMg9+1vPFEqBpq4ZkbxeMP/YPH/sF5PomkkY3kSSbwq6TB//3Q39zeSEb7xDO+lnUdDXrvVa99bjFQ+Djn87Y/7RRkcMs2CGWP70EXmSV1CMkfiC0/hmwlK5g0OS0/bPmFw9G5q+z2HXSBH59kee9ddnFfUGYeXfL42akg4GYTkIry634azYOPobFirAupRhkjUgz0/ZQrNDcFNjOuz4sdUIZiZiDq10jH0DisntmDC9YZ4IbO9xigwfEbnx8v8cxq0kUNVCm5wgl95asA5W9P733bwLuiGDjOsi0Q4A27ZJw+iie8BPiVwEMiEMHoBjbJfQki45/XoVwg=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale-system
