# Jellyfin
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: servarr
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "jellyfin.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-jellyfin
          port: 8096
---
# Jellyseerr
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyseerr
  namespace: servarr
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "jellyseerr.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-jellyseerr
          port: 5055
---
# Prowlarr
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prowlarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "prowlarr.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-prowlarr
          port: 9696
---
# Sonarr
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "sonarr.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-sonarr
          port: 80
---
# Radarr
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "radarr.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-radarr
          port: 7878
---
# qBittorrent
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
  namespace: servarr
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "qbittorrent.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-qbittorrent-web
          port: 8080
---
# Bazarr
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bazarr
  namespace: servarr
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "bazarr.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: servarr-bazarr
          port: 6767
