# cloudflare wants a secret formatted like
# {
#     "AccountTag": "ACCOUNT_ID",
#     "TunnelID": "TUNNEL_ID",
#     "TunnelSecret": "YOUR_BASE64_TUNNEL_SECRET_HERE"
# }
# The key must be named credentials.json

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgB1WkzeuWvIwX0jrmvfKTwr32DLVn9tDFHauQFaFpTKuoX13wOY1lOyV+GwDd4lSbNw5w6BWSptS3+SqmoAZXWM6/QOU8mgfZuiatfw+qalIjfh4SCweY9UBR5hE2crXtIhlMsbkW8+F39+AewssjLr3eHJKyHbaCeQSQ3Mb7eAKEuvi0+3TK3zC/nic4ouranyY00AmMCin/SBhLShRIAVCSl1wE4tomot1DsvxHk9N52MA/06X99Rf1ZAmhobG9aog7wjQtcG7spR04eJvbh54jbNHzsn0mI+mDat8hv4ysh4a/E4ASlcQqumATUxVkIEhtYgh6t64TjucRSUzsXwes/zUxRVKJ7frpYOaGEAoDiYm0ZPCNtgdC+1SZ1YFWbuxmxPbjd8CevFaGZfkwVfT+p/2smwBzCURdeOyC4Mb1jZUNAY3PsXGTM++Gk2j5JyqfoSW74f0sZQ0RG/WSGK6dkHcdYP8v7Po+nFZMBX7otvUVqkoMeKZUyZiIbYC4dZxWjMJ+u7mEzFrlXD2o25Mu4PAI8jv6GWmX3CWeDsKX1Qd/rp8aIIdAeD3sa3eK93eMOIF5iKEtFPFzh5Kr1YK4APEOqpzDJsFdQhcRlodX2tkepnkWZLfI6O3LKTl1Wj1fDWf4IqCKyxkx6anY8G7NAd44JJRHbmmF9mryGyS9vsbrynKbliqXxHEH0DnZ4juT0ObhFYB9lTew9UUajBnjZlcDxv4HwZaUbmBHWDxf6K9n1Kyl4aUR411gydmjm3Lf0KHtgNgfYyKR5RUAbp1rhoxpbEkjazhILlp0crqKsNL3wyckpAaPVorPcCJZDQjJEwmThzlCjCM/Pi/F/FlTiVwLGn+8rNSccDDAUz3N4IHcELeTALZxee54tmdEAPAaUGnqB3aATIoHA5+AP1/99xszql48siLVarvmJx6U98sjywl/W6N/gGAAHEWWmrLXvzvJ388j9osCFS
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
