apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-michaelmuzafarov-dev
  namespace: envoy-gateway-system
spec:
  secretName: wildcard-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "michaelmuzafarov.dev"
    - "*.michaelmuzafarov.dev"
