apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-secret
  namespace: cert-manager
spec:
  encryptedData:
    email: AgAOJaiG6kveJSZQgYAsOPJqAbkr2eJIAnOXbl3EDgPPQmqWM0JbneVYiufnKu9Dhlf+1lUng9N4h5gOYhP5g41/sRAdjYXsd6QM9S1TMWyNhSIOJRD4Eo4c/Rdbnaxqe+iEykVbWwlv7no8raGws3x8DjxGKPzgo5R8j+RUbVWpZGtynBkiLWg5PCP0TL9kf3fIrH5yIdl4k0bmhpHtue0CK1mWk2cr2XzJ4lAxmJm+oY1mqYYbY6Hvp/15bI5IDVLEkfsPg8LL/xtR1zqBCnpHsdaZ2H2J4KLQjvpSOiPiQyTIfdjWKy6wCmjQQ8procsy08/puzwF0sYzVK3Tnd4C84fKinmNkvfzlDr5Vi0FAcHpvFNN9CERRIo6w5DHNqUdXmH2T3oiPBnh72k4BKBTrQlk4XxpqYWRM3ZHi2XHXHF1R/eSk2usTC6VLlvtBzpJRWmfNO6JN/Ug86/JMaNUovWYpKTEO8vPjLtvY4L713Z184S4lQqBceMpKK1UkRGnU6o1GtVYgqUtT6Lr05Co7M/YSJvaw40ffriYd5Kba/oUihnmR/w5+lF6UE7wVu6RlgdXFBv1/K9IZuVn3XnRKZ8aOdJ3u0W4V8JU4FUSqT84vJZW7UPxdEPlyhA6Z1zq9yfF/xxvk3O8PAr9yVcUzUBmTjvgOYAd8s5ucr8fC57KfcpVevdSnTVdL67PBuM5iSCDdwpBFIDJzQIjywq45sJzDmk=
    dns-api-token: AgAhLMb/QS2Xv/pPc6Z7NannUl4pitL9qPmdzYOYfCQ7eVmmBXuuA4wVzv5TVzJOEgzpUUKOHwgwn40YuiGQ1BvNxOiM8JM/LHL48Sc8LnVG89y/uXhnY/DzsjPlUebY1V/Ox/Lu8Euhs4B4B4Nb01MnYn2oCmjgKDgElNjxNU84aNEYxiErWtwoqzS9C9v03UT1AkNlcgbhmdA1TEo0TlAuoVm4i2ii0rwGXGrk6D0ypzBDQv2+WvcqzS86B6OgeiLsv8K5orXCdn0ol5tR1HyXeb//7C4ZfjKRfnQ9l2tlS3E1YZcNbn4dpNpB+/ITGsbr5hzH4bNRVg+G/90OS+v64paaSQdXZ8J1ry2WqpZXpad73uTLRtOxI9atxzodav/KvggQe98664Pbc4bDdNm/9swLg2GuTDij9nulbEhZsf3UGo5QhuDJnjxdMFgn7QqhSOTLxNHN11MrpyJOr3L5DXp/2JdA2rpnOdfPrKvFqUiZo7JmbrqZdd3VM5AjMJH7Dnjk8kfYkIiC/D2zTDGmuHmDfC4j9pN0FEGls9ICoLebkXJyJM4WGs0yWl2zJrJgI4bQgD0Kn6N9V6d+gxzQA8swVIFCmQ5ZB/aA9dlJC+LfFDhSlNt9T/fyIMWoa1I6IgsrUBeIUXbn6h3WXlYqrIpdUCCE75JeXe/akC9uczsBIC3FlDXq5s0ITBZoq6twd21Es/V/5N73obN59VN6ah34o39Uxhl7a2AoVXwnhlBwCAWYFeI3
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-secret
      namespace: cert-manager
    type: Opaque
