apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-secret
  namespace: traefik-system
spec:
  encryptedData:
    email: AgAFo1i4roCAJaorFvkS0UCiiAaw4vJAeS+nzjWYvFMkmXErOyGd3yXi2WkekI2oottdpS9P778nTR21+7vB5Xfl8ItgD3w6qmPaXFmPFzF6hI5JX6Yy2G6VkOM985wE+2xavWsNv9eiyCw/QyG8knPo6yrpg3sTapEKjpgE7rcXSd9ZP0xSe9vyRIoX1sbCgQgs8F2aWq1Y1SHo0ENhbF6DOvQfS2mdmhlbyziteFhkJkuEZN4ugQkS22p6oW2GFZmqxYi444DS/GcrwscV/N4TLxLZwGHd/iAyvOWnwQZOD4K1yisEjP/bS3WWFgZuIaBSML5I1DvTeqrovjEFkNosJVKGhLgPvtI/RXfsN3yrfFhWjPykLX/syfCRkON3qZdghRO0q6wWUH9Cp+4BdVqQBVO2FH7cOnx3qlF/7h4cXp6AbG3ve3BtHX4LapRTly8xKUvuMOPlSnlaDarPqLR9iGkdD8tpCUsFN2kPlQ7cyk7psE3Sxt+iUZ9cOkcbOhM9oX7I2FYe4wd2EhXyoeF7m1EQB+WRyv7quLqAXWLP7i7T2hVdsgmVAo/5irO66WSoOQ3TyCuzFvauUYulhHmFucvBqI27On91ETbpWbScYqlLPuZjb0blgTk2hh5n05PPh4AkBpRGXtx5JscNoXTsR/ewCNJUwRHi+1RyFXxTkETN0Y/KrH7kW/ESmfZbwRKZFV4OgeuLFrTc4Htnz2frSg2mbSM=
    dns-api-token: AgByShwOEDmzOrf4p4tYNjMOolxgJSRWTrBrNnEQqUJKS80JSqQJn4v5z0Q9YK/9X0CbcsgulVgjh5IaaIOsiyL0Bg3E+EN3kOCQXqemYvNFHN/EncZURrLV8uAhZ38e0d3ZbeuIxOw+4FDnN216DBBceDW0U9kNx8gQkLaVJtfD8vEJibP0KmUJRJWsb7blGsSNcngyQEt85JMzDRrKqHWRIGSm3dpIxtNIzfuva17YmAHFpDlL7d7ah3H5zzr2gFZ0GlLIxKa9SWRCa7Aoa4S4TQZi1XFHkeOxN1DQPLMBjUImVCkRsAngfd4OpgTgSWx1OBVkdFXRXOt7wtdmNax3hpUURZCOfB+5Ryj0LE8hniJTr64ZBn4cqsUBnvzZI4zzgzCbBKpyxVs1wGFYa3re094c+XrOkCDj0lzJUneUMGrmqJ1TpVFzSpm6gDLZvrGaxKB1NlbSuLiLVv+F687inGgc1uC4fjfrWxJgQEnxz3MjZB9gx9jJPiuOMUEtF7jeZrw+gyf5Cmf4wxB3yefrnO/q1QoFAJ/qV565Rqwybo3m2nsbx2pMkHa8T4jAK21hUbJkIMozAiHbcLay2zsDDORYpMZHV6C1VvZejj3S3uc53uFwea5ZQB6aaroIJbCrbukdyh3K8s6xQeF/oApGBpCx/2hRKjuguqW6bYwjf4CgtrByrcSrRASiBkESVRq8wVOYeDFcEAMI3DktHFR1XIuaMT5LUWoQMxeIVNlUBm+NdDMv7SCU
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-secret
      namespace: traefik-system
