# HTTP (Cloudflare Tunnel traffic)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-http
  namespace: immich
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "immich.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: immich-server
          port: 2283
      timeouts:
        request: 10m
---
# HTTPS (Tailscale traffic)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-https
  namespace: immich
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - "immich.michaelmuzafarov.dev"
  rules:
    - backendRefs:
        - name: immich-server
          port: 2283
      timeouts:
        request: 10m
